---
substitutions:
  name: sonoff-mini-r2
  friendly_name: Sonoff Mini R2
  comment: Sonoff Mini R2 Smart Switch

  # Underlying restore mode for the switch
  switch_restore_mode: "RESTORE_DEFAULT_OFF"

packages:
  base: !include modules/base.yaml

esphome:
  min_version: 2024.6.0
  project:
    name: "Sonoff.Mini R2"
    version: "v2.0.0-scsole"
  on_boot:
    - priority: 600
      then:
        - select.set_index:
            id: power_mode
            index: !lambda |-
              return id(restore_mode) - 1;
        - lambda: |-
            switch(id(restore_mode))
            {
              case 1:
              {
                id(relay_1).turn_off();
                break;
              }
              case 2:
              {
                id(relay_1).turn_on();
                break;
              }
              default:
              {
                break;
              }
            }

esp8266:
  board: esp01_1m
  restore_from_flash: true

dashboard_import:
  package_import_url: github://scsole/esphome-device-configs/sonoff-mini-r2.yaml
  import_full_config: false

globals:
  - id: restore_mode
    type: int
    restore_value: yes
    initial_value: "3" # 1 = Always_Off, 2 = Always_On, 3 = Restore_State

select:
  - platform: template
    name: "Power On State"
    id: power_mode
    optimistic: true
    icon: mdi:electric-switch
    options:
      - Always Off
      - Always On
      - Restore State
    on_value:
      then:
        - lambda: |-
            id(restore_mode) = i + 1;
    entity_category: config

binary_sensor:
  # Built-in button
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: Button
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.1s
        then:
          - light.toggle: light_1
      - timing:
          - ON for at least 4s
        then:
          - button.press: factory_reset_button

  # External switch
  - platform: gpio
    name: Input
    pin:
      number: GPIO4
      inverted: true
    id: switch_1
    disabled_by_default: true
    # Edge
    # on_press:
    #   then:
    #     - light.toggle: light_1
    # on_release:
    #   then:
    #     - light.toggle: light_1
    # Toggle
    on_press:
      then:
        - light.turn_on: light_1
    on_release:
      then:
        - light.turn_off: light_1

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: Light
    output: relay_1
    id: light_1
    restore_mode: ${switch_restore_mode}

  - platform: status_led
    name: Status LED
    pin:
      number: GPIO13
      inverted: true
    entity_category: config
    disabled_by_default: true
