---
substitutions:
  # Device defaults
  device_name: sonoff-basic-r2
  friendly_name: Sonoff Basic R2
  device_description: Sonoff DIY Smart Switch
  channel_1_name: Light

  # Project info
  project_name: "sonoff.basic-r2"
  project_version: "1.3"

  # Credentials
  wifi_password: "12345678"

esphome:
  name: "${device_name}"
  name_add_mac_suffix: true
  friendly_name: "${friendly_name}"
  comment: "${device_description}"
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp01_1m
  restore_from_flash: true

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating.
ota:
  reboot_timeout: 10min
  num_attempts: 5

# Public location of this yaml file.
dashboard_import:
  package_import_url: github://scsole/esphome-device-configs/sonoff-basic-r2.yaml@main

wifi:
  # Setup a wifi access point.
  ap:
    password: "${wifi_password}"

# In combination with wifi `ap`, allow the user to provision wifi credentials to the device.
captive_portal:

binary_sensor:
  - platform: gpio
    name: Button
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.01s
        then:
          - light.toggle: light_1
      - timing:
          - ON for at least 4s
        then:
          - button.press: reset

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: "${channel_1_name}"
    output: relay_1
    id: light_1

status_led:
  pin:
    number: GPIO13
    inverted: true

button:
  - platform: restart
    name: Restart
  - platform: factory_reset
    name: Restart with Factory Default Settings
    disabled_by_default: true
    id: reset

sensor:
  - platform: wifi_signal
    name: WiFi Signal dB
    id: wifi_signal_db
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    mac_address:
      name: Mac Address
